spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/banking?currentSchema=banking
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
jwt:
    secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
    lifetime: 10m
