spring:
    config:
      import: optional:file:.env[.properties]
    datasource:
      url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
jwt:
    secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
    lifetime: 10m